[package]
name = "fuel-vm-rust"
version = "0.1.0"
authors = ["Shahan Khatchadourian <shahan.k.code@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.10"
sha2 = "0.9"
sha3 = "0.9"
secp256k1 = {version="0.20", features=["recovery"]}
tracing = "0.1"
tracing-subscriber = {version="0.2", optional=true}
clap = {version="2.33", optional=true}
json = {version="0.12", optional=true}

[dev-dependencies]
rand = "0.8"

[features]
log = ["tracing-subscriber"]
cli = ["clap", "json"]

[[bin]]
name = "interpreter"
required-features = ["log", "cli"]
