[package]
name = "fuel-vm-rust"
version = "0.1.0"
authors = ["Shahan Khatchadourian <shahan.k.code@gmail.com>"]
edition = "2018"

[dependencies]
sha2 = "0.9"
sha3 = "0.9"
secp256k1 = {version="0.20", features=["recovery"]}

[dev-dependencies]
rand = "0.8"
