[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
async-process = "1.3"
axum = "0.4"
async-std = "1.10.0"
fuel-core = { version = "0.2" }
fuel-indexer-schema = { path = "../schema", features = ["graphql-types"] }
fuel-wasm-executor = { path = "../indexer" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_yaml = "0.8.19"
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.5", features = ["with-serde_json-1"] }
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["env-filter"] }
