[package]
name = "fuel-indexer-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
graphql-parser = "0.3"
itertools = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }

[features]
default = ["db-sqlite"]
db-sqlite = []
db-postgres = []
