[package]
name = "fuel-indexer-schema"
version = "0.0.0"
edition = "2021"
license = "BUSL-1.1"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0"
diesel = { version = "1.4", optional = true, features = ["serde_json"] }
fuel-indexer-graphql = { path = "../graphql" }
fuel-tx = { version = "0.6", default-features = false }
fuel-types = { version = "0.3", default-features = false }
graphql-parser = "0.3"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
insta = "1.8"

[features]
default = ["fuel-types/serde-types-minimal"]
diesel-postgres = ["derive-utils", "diesel/postgres"]
diesel-sqlite = ["derive-utils", "diesel/sqlite"]
derive-utils = ["fuel-types/default", "fuel-types/serde-types"]
